apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-test-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:thegodeveloper/gitops-argocd.git
    targetRevision: HEAD
    path: dev
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: "3s"
        factor: 2
        maxDuration: "2m"